#if 0
#elif defined(__arm64__) && __arm64__
// Generated by Apple Swift version 6.3.3 effective-5.10 (swiftlang-6.3.3.1.3 clang-2100.1.1.101)
#ifndef SMARTPROMOCORE_SWIFT_H
#define SMARTPROMOCORE_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#if defined(__OBJC__)
#include <Foundation/Foundation.h>
#endif // defined(__OBJC__)
#if defined(__cplusplus)
#include <cstdint>
#include <cstddef>
#include <cstdbool>
#include <cstring>
#include <stdlib.h>
#include <new>
#include <type_traits>
#else
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include <string.h>
#endif
#if defined(__cplusplus)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wnon-modular-include-in-framework-module"
#if defined(__arm64e__) && __has_include(<ptrauth.h>)
# include <ptrauth.h>
#else
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wreserved-macro-identifier"
# ifndef __ptrauth_swift_value_witness_function_pointer
#  define __ptrauth_swift_value_witness_function_pointer(x)
# endif
# ifndef __ptrauth_swift_class_method_pointer
#  define __ptrauth_swift_class_method_pointer(x)
# endif
#pragma clang diagnostic pop
#endif
#pragma clang diagnostic pop
#endif

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef unsigned char char8_t;
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...) 
# endif
#endif
#if !defined(SWIFT_RUNTIME_NAME)
# if __has_attribute(objc_runtime_name)
#  define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
# else
#  define SWIFT_RUNTIME_NAME(X) 
# endif
#endif
#if !defined(SWIFT_COMPILE_NAME)
# if __has_attribute(swift_name)
#  define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
# else
#  define SWIFT_COMPILE_NAME(X) 
# endif
#endif
#if !defined(SWIFT_METHOD_FAMILY)
# if __has_attribute(objc_method_family)
#  define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
# else
#  define SWIFT_METHOD_FAMILY(X) 
# endif
#endif
#if !defined(SWIFT_NOESCAPE)
# if __has_attribute(noescape)
#  define SWIFT_NOESCAPE __attribute__((noescape))
# else
#  define SWIFT_NOESCAPE 
# endif
#endif
#if !defined(SWIFT_RELEASES_ARGUMENT)
# if __has_attribute(ns_consumed)
#  define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
# else
#  define SWIFT_RELEASES_ARGUMENT 
# endif
#endif
#if !defined(SWIFT_WARN_UNUSED_RESULT)
# if __has_attribute(warn_unused_result)
#  define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
# else
#  define SWIFT_WARN_UNUSED_RESULT 
# endif
#endif
#if !defined(SWIFT_NORETURN)
# if __has_attribute(noreturn)
#  define SWIFT_NORETURN __attribute__((noreturn))
# else
#  define SWIFT_NORETURN 
# endif
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA 
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA 
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA 
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif
#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif
#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER 
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility) 
# endif
#endif
#if !defined(SWIFT_ENUM)
# if (defined(__cplusplus) && __cplusplus >= 201103L) ||      (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 202311L) ||      __has_feature(objc_fixed_enum)
#  define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
#  if __has_feature(generalized_swift_name)
#   define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
#  else
#   define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
#  endif
# else
#  define SWIFT_ENUM(_type, _name, _extensibility) _type _name; enum 
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_ENUM_TAG)
# if (defined(__cplusplus) && __cplusplus >= 201103L) ||      (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 202311L) ||      __has_feature(objc_fixed_enum)
#  define SWIFT_ENUM_TAG enum
# else
#  define SWIFT_ENUM_TAG
# endif
#endif
#if !defined(SWIFT_ENUM_FWD_DECL)
# if (defined(__cplusplus) && __cplusplus >= 201103L) ||      (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 202311L) ||      __has_feature(objc_fixed_enum)
#  define SWIFT_ENUM_FWD_DECL(_type, _name) enum _name : _type;
# else
#  define SWIFT_ENUM_FWD_DECL(_type, _name) typedef _type _name;
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_AVAILABILITY_DOMAIN)
# define SWIFT_AVAILABILITY_DOMAIN(dom, ...) __attribute__((availability(domain: dom, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if !defined(SWIFT_DEPRECATED_OBJC)
# if __has_feature(attribute_diagnose_if_objc)
#  define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
# else
#  define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
# endif
#endif
#if defined(__OBJC__)
#if !defined(IBSegueAction)
# define IBSegueAction 
#endif
#endif
#if !defined(SWIFT_EXTERN)
# if defined(__cplusplus)
#  define SWIFT_EXTERN extern "C"
# else
#  define SWIFT_EXTERN extern
# endif
#endif
#if !defined(SWIFT_CALL)
# define SWIFT_CALL __attribute__((swiftcall))
#endif
#if !defined(SWIFT_INDIRECT_RESULT)
# define SWIFT_INDIRECT_RESULT __attribute__((swift_indirect_result))
#endif
#if !defined(SWIFT_CONTEXT)
# define SWIFT_CONTEXT __attribute__((swift_context))
#endif
#if !defined(SWIFT_ERROR_RESULT)
# define SWIFT_ERROR_RESULT __attribute__((swift_error_result))
#endif
#if defined(__cplusplus)
# define SWIFT_NOEXCEPT noexcept
#else
# define SWIFT_NOEXCEPT 
#endif
#if !defined(SWIFT_C_INLINE_THUNK)
# if __has_attribute(always_inline)
# if __has_attribute(nodebug)
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline)) __attribute__((nodebug))
# else
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline))
# endif
# else
#  define SWIFT_C_INLINE_THUNK inline
# endif
#endif
#if defined(_WIN32)
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL __declspec(dllimport)
#endif
#else
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL 
#endif
#endif
#if !__has_feature(nullability)
# define _Nonnull
# define _Nullable
# define _Null_unspecified
#elif !defined(__OBJC__)
# pragma clang diagnostic ignored "-Wnullability-extension"
#endif
#if !__has_feature(nullability_nullable_result)
# define _Nullable_result _Nullable
#endif
#if __has_feature(objc_modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
#endif

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"
#pragma clang diagnostic ignored "-Wunsafe-buffer-usage"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="SmartPromoCore",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__cplusplus)
extern "C" {
#endif

#if defined(__cplusplus)
} // extern "C"
#endif
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#if defined(__OBJC__)
#if __has_feature(objc_modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import CoreFoundation;
@import Foundation;
@import ObjectiveC;
@import UIKit;
#endif

#import <SmartPromoCore/SmartPromoCore.h>

#endif // defined(__OBJC__)
#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"
#pragma clang diagnostic ignored "-Wunsafe-buffer-usage"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="SmartPromoCore",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__OBJC__)

@protocol FSPThemed;
@class NSCoder;
@class UIViewController;
SWIFT_CLASS("_TtC14SmartPromoCore7FSPView")
@interface FSPView : UIView
@property (nonatomic, strong) id <FSPThemed> _Nonnull themed;
- (nonnull instancetype)initWithThemed:(id <FSPThemed> _Nonnull)themed OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
- (void)setupUI;
/// Subclasses override this to update colors according to <code>fspThemed</code>
- (void)updateColors;
/// Easily attaches this view to a view controller’s root view (full screen).
- (void)attachTo:(UIViewController * _Nonnull)viewController;
- (void)viewDidAppear;
- (nonnull instancetype)initWithFrame:(CGRect)frame SWIFT_UNAVAILABLE;
@end

@class UIScrollView;
@class UIStackView;
SWIFT_CLASS("_TtC14SmartPromoCore17FSPScrollableView")
@interface FSPScrollableView : FSPView
@property (nonatomic, readonly, strong) UIScrollView * _Nonnull scrollView;
@property (nonatomic, readonly, strong) UIView * _Nonnull contentView;
/// StackView for easy adding subviews
@property (nonatomic, readonly, strong) UIStackView * _Nonnull stackView;
- (void)setupUI;
/// Adds a flexible spacer to the stack view that pushes content below it to the bottom
- (UIView * _Nonnull)addFlexibleSpacer;
/// Adds a fixed-height spacer to the stack view, accounting for stackView spacing
/// \param height Total desired spacing between items
///
- (UIView * _Nonnull)addFixedSpacerWithHeight:(CGFloat)height;
- (nonnull instancetype)initWithThemed:(id <FSPThemed> _Nonnull)themed OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end

@class UITextField;
SWIFT_CLASS("_TtC14SmartPromoCore11FSPFormView")
@interface FSPFormView : FSPScrollableView <UITextFieldDelegate>
- (void)textFieldDidBeginEditing:(UITextField * _Nonnull)textField;
- (BOOL)textFieldShouldBeginEditing:(UITextField * _Nonnull)textField SWIFT_WARN_UNUSED_RESULT;
- (BOOL)textFieldShouldReturn:(UITextField * _Nonnull)textField;
- (nonnull instancetype)initWithThemed:(id <FSPThemed> _Nonnull)themed OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end

@class FSPButtonText;
@class NSString;
SWIFT_CLASS("_TtC14SmartPromoCore16FSPBaseOptInView")
@interface FSPBaseOptInView : FSPFormView
@property (nonatomic, copy) void (^ _Nullable action)(void);
@property (nonatomic, strong) FSPButtonText * _Nonnull actionButton;
- (void)setupWithTitle:(NSString * _Nonnull)title button:(NSString * _Nonnull)button;
- (void)setupUI;
- (void)actionTap;
- (nonnull instancetype)initWithThemed:(id <FSPThemed> _Nonnull)themed OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS("_TtC14SmartPromoCore18FSPCartBottomSheet")
@interface FSPCartBottomSheet : NSObject
- (void)showAbove:(UIViewController * _Nonnull)above;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class UIImage;
/// The cart icon for the navigation bar with the count baked in — the <em>pre-iOS 26 fallback only</em>.
/// From 26 on, <code>FSPPrizesViewController.updateCartButton</code> uses the system <code>UIBarButtonItem.badge</code>
/// and this is not called; delete it when the deployment target reaches 26.
/// Before 26 a bar item draws either its image or its title, never both, and has no badge, so the
/// count is drawn into the image: the SF Symbol, a filled pill, and the number knocked out of the
/// pill. It stays monochrome and is vended as a template image on purpose, and that is the whole
/// point: the item goes on inheriting the navigation bar tint that <code>setupHeader</code> resolves (white
/// over the colored header, <code>textSecondary</code> otherwise). A two-colour badge would mean painting the
/// symbol by hand too, and getting it wrong on one of the two headers.
SWIFT_CLASS("_TtC14SmartPromoCore11FSPCartIcon")
@interface FSPCartIcon : NSObject
+ (UIImage * _Nullable)imageWithCount:(NSInteger)count SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class UIColor;
SWIFT_CLASS("_TtC14SmartPromoCore26FSPCircularProgressBarView")
@interface FSPCircularProgressBarView : UIView
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) Class _Nonnull layerClass;)
+ (Class _Nonnull)layerClass SWIFT_WARN_UNUSED_RESULT;
@property (nonatomic) NSInteger value;
@property (nonatomic) NSInteger maxValue;
@property (nonatomic) CGFloat borderPadding;
@property (nonatomic) CGFloat progressAngle;
@property (nonatomic) CGFloat progressRotationAngle;
@property (nonatomic) CGFloat progressLineWidth;
@property (nonatomic, strong) UIColor * _Nonnull progressColor;
@property (nonatomic, strong) UIColor * _Nonnull progressStrokeColor;
@property (nonatomic) CGFloat emptyLineWidth;
@property (nonatomic, strong) UIColor * _Nonnull emptyLineColor;
@property (nonatomic, strong) UIColor * _Nonnull emptyLineStrokeColor;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end

@class UILabel;
@class UIImageView;
SWIFT_CLASS("_TtC14SmartPromoCore20FSPFeatureHeaderView")
@interface FSPFeatureHeaderView : UIView
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) CGFloat contentHeight;)
+ (CGFloat)contentHeight SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) CGFloat contentTopPadding;)
+ (CGFloat)contentTopPadding SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) CGFloat contentBottomPadding;)
+ (CGFloat)contentBottomPadding SWIFT_WARN_UNUSED_RESULT;
@property (nonatomic, readonly, strong) UILabel * _Nonnull headnoteLabel;
@property (nonatomic, readonly, strong) UILabel * _Nonnull titleLabel;
@property (nonatomic, readonly, strong) UILabel * _Nonnull messageLabel;
@property (nonatomic, readonly, strong) UIImageView * _Nonnull iconView;
@property (nonatomic, readonly, strong) FSPCircularProgressBarView * _Nonnull progressView;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end

@class UIFont;
@class NSAttributedString;
SWIFT_CLASS("_TtC14SmartPromoCore13FSPHTMLParser")
@interface FSPHTMLParser : NSObject
+ (NSAttributedString * _Nullable)parseNativeWithHtml:(NSString * _Nonnull)html font:(UIFont * _Nullable)font alignment:(NSTextAlignment)alignment SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS("_TtC14SmartPromoCore18FSPKeyboardToolbar")
@interface FSPKeyboardToolbar : UIToolbar
+ (FSPKeyboardToolbar * _Nonnull)instanceWithTitle:(NSString * _Nonnull)title tintColor:(UIColor * _Nonnull)tintColor target:(id _Nonnull)target action:(SEL _Nonnull)action SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS("_TtC14SmartPromoCore8FSPLabel")
@interface FSPLabel : UILabel
@property (nonatomic) IBInspectable UIEdgeInsets padding;
- (void)drawTextInRect:(CGRect)rect;
- (CGRect)textRectForBounds:(CGRect)bounds limitedToNumberOfLines:(NSInteger)numberOfLines SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end

@class SPSFSPConsumerCore;
SWIFT_CLASS("_TtC14SmartPromoCore20FSPOptInBaseFormView")
@interface FSPOptInBaseFormView : FSPBaseOptInView
@property (nonatomic, readonly, strong) SPSFSPConsumerCore * _Nonnull consumer;
- (nonnull instancetype)initWithConsumer:(SPSFSPConsumerCore * _Nonnull)consumer filter:(NSArray<NSString *> * _Nullable)filter themed:(id <FSPThemed> _Nonnull)themed OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
- (void)actionTap;
- (void)textFieldDidBeginEditing:(UITextField * _Nonnull)textField;
- (BOOL)textField:(UITextField * _Nonnull)textField shouldChangeCharactersInRange:(NSRange)range replacementString:(NSString * _Nonnull)string SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)initWithThemed:(id <FSPThemed> _Nonnull)themed SWIFT_UNAVAILABLE;
@end

@class FSPTextField;
SWIFT_CLASS("_TtC14SmartPromoCore17FSPMyDataFormView")
@interface FSPMyDataFormView : FSPOptInBaseFormView
@property (nonatomic, strong) FSPTextField * _Nonnull cpfTextField;
- (void)setupUI;
- (void)buildFields;
- (void)actionTap;
- (nonnull instancetype)initWithConsumer:(SPSFSPConsumerCore * _Nonnull)consumer filter:(NSArray<NSString *> * _Nullable)filter themed:(id <FSPThemed> _Nonnull)themed OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end

@class SPSFSPAuthRequired;
@class FSPCodeInput;
SWIFT_CLASS("_TtC14SmartPromoCore16FSPOptInAuthView")
@interface FSPOptInAuthView : FSPBaseOptInView
- (nonnull instancetype)initWithAuthRequired:(SPSFSPAuthRequired * _Nonnull)authRequired themed:(id <FSPThemed> _Nonnull)themed OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder SWIFT_UNAVAILABLE;
@property (nonatomic, strong) FSPCodeInput * _Nonnull codeTextField;
- (void)setupOptInUI;
- (void)viewDidAppear;
- (void)actionTap;
- (nonnull instancetype)initWithThemed:(id <FSPThemed> _Nonnull)themed SWIFT_UNAVAILABLE;
@end

@class UIPickerView;
@interface FSPOptInBaseFormView (SWIFT_EXTENSION(SmartPromoCore)) <UIPickerViewDataSource, UIPickerViewDelegate>
- (NSInteger)numberOfComponentsInPickerView:(UIPickerView * _Nonnull)pickerView SWIFT_WARN_UNUSED_RESULT;
- (NSInteger)pickerView:(UIPickerView * _Nonnull)pickerView numberOfRowsInComponent:(NSInteger)component SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nullable)pickerView:(UIPickerView * _Nonnull)pickerView titleForRow:(NSInteger)row forComponent:(NSInteger)component SWIFT_WARN_UNUSED_RESULT;
- (void)pickerView:(UIPickerView * _Nonnull)pickerView didSelectRow:(NSInteger)row inComponent:(NSInteger)component;
@end

SWIFT_CLASS("_TtC14SmartPromoCore16FSPOptInFormView")
@interface FSPOptInFormView : FSPOptInBaseFormView
- (nonnull instancetype)initWithConsumer:(SPSFSPConsumerCore * _Nonnull)consumer filter:(NSArray<NSString *> * _Nullable)filter themed:(id <FSPThemed> _Nonnull)themed OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS("_TtC14SmartPromoCore14FSPOptInIDView")
@interface FSPOptInIDView : FSPBaseOptInView
@property (nonatomic, strong) FSPTextField * _Nonnull cpfTextField;
- (void)setupOptInUI;
- (void)viewDidAppear;
- (void)actionTap;
- (nonnull instancetype)initWithThemed:(id <FSPThemed> _Nonnull)themed OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end

@class SPSFSPPrizeItem;
/// <code>.horizontal</code> is the list’s card, image beside the text; <code>.vertical</code> is the grid’s tile, image
/// over the text.
SWIFT_CLASS("_TtC14SmartPromoCore16FSPPrizeCardView")
@interface FSPPrizeCardView : UIView
@property (nonatomic, copy) void (^ _Nullable onAction)(SPSFSPPrizeItem * _Nonnull);
- (nonnull instancetype)initWithAxis:(UILayoutConstraintAxis)axis OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)bind:(SPSFSPPrizeItem * _Nonnull)prize hasCart:(BOOL)hasCart themed:(id <FSPThemed> _Nonnull)themed;
- (nonnull instancetype)initWithFrame:(CGRect)frame SWIFT_UNAVAILABLE;
@end

SWIFT_CLASS("_TtC14SmartPromoCore12FSPPrizeCell")
@interface FSPPrizeCell : UICollectionViewCell
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)bind:(SPSFSPPrizeItem * _Nonnull)prize hasCart:(BOOL)hasCart themed:(id <FSPThemed> _Nonnull)themed onAction:(void (^ _Nonnull)(SPSFSPPrizeItem * _Nonnull))onAction;
@end

SWIFT_CLASS("_TtC14SmartPromoCore16FSPPrizeGridCell")
@interface FSPPrizeGridCell : FSPPrizeCell
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end

@class NSBundle;
SWIFT_CLASS("_TtC14SmartPromoCore29FSPPrizeHistoryViewController")
@interface FSPPrizeHistoryViewController : FSPBaseViewController
- (void)viewDidLoad;
- (void)viewWillAppear:(BOOL)animated;
- (nonnull instancetype)initXib:(NSString * _Nonnull)xibName OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end

@class UITableView;
@class NSIndexPath;
@class UITableViewCell;
@interface FSPPrizeHistoryViewController (SWIFT_EXTENSION(SmartPromoCore)) <UITableViewDataSource>
- (UIView * _Nullable)tableView:(UITableView * _Nonnull)tableView viewForHeaderInSection:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
/// A consumer who has redeemed nothing still reaches the screen from the home card, so the
/// empty copy takes the single row the timeline would have had.
- (NSInteger)tableView:(UITableView * _Nonnull)tableView numberOfRowsInSection:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
- (UITableViewCell * _Nonnull)tableView:(UITableView * _Nonnull)tableView cellForRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
@end

@class SPSFSPSharedPrizeHistoryViewModelState;
SWIFT_CLASS("_TtC14SmartPromoCore24FSPPrizeHistoryViewModel")
@interface FSPPrizeHistoryViewModel : NSObject
/// Subscribes, delivering the current state right away — the screen never draws an empty frame.
/// The shared ViewModel collects on <code>Dispatchers.Main</code>, so this already arrives on the main
/// thread and needs no <code>FSPDispatchQueue</code> hop.
- (void)observe:(void (^ _Nonnull)(SPSFSPSharedPrizeHistoryViewModelState * _Nonnull))onState;
/// Rebuilds from the campaign already in memory, without a fetch.
- (void)reload;
/// Re-fetches the campaign — pull-to-refresh, and coming back from a redemption.
- (void)refresh;
- (void)clear;
/// Waiting at the counter, or picked up. Mirrored by the timeline dot and by the pickup line.
- (UIColor * _Nonnull)statusColorWithPending:(BOOL)pending SWIFT_WARN_UNUSED_RESULT;
- (UIImage * _Nullable)statusIconWithPending:(BOOL)pending SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

/// One square of the stamp card: a slice of points, or the prize that closes it.
SWIFT_CLASS("_TtC14SmartPromoCore17FSPPrizeStampCell")
@interface FSPPrizeStampCell : UICollectionViewCell
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)bindStamped:(BOOL)stamped points:(NSInteger)points themed:(id <FSPThemed> _Nonnull)themed;
- (nonnull instancetype)bindPrize:(SPSFSPPrizeItem * _Nonnull)prize alsoHolding:(NSInteger)otherPrizes selected:(BOOL)selected themed:(id <FSPThemed> _Nonnull)themed;
@end

@class UIEvent;
/// Floats over the stamp card while a prize is picked: confirm it, or drop the pick.
SWIFT_CLASS("_TtC14SmartPromoCore23FSPPrizeStampFooterView")
@interface FSPPrizeStampFooterView : UIView
@property (nonatomic, copy) void (^ _Nullable onAction)(void);
@property (nonatomic, copy) void (^ _Nullable onClear)(void);
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
/// Only the controls take a touch; the rest passes through to the card underneath.
- (UIView * _Nullable)hitTest:(CGPoint)point withEvent:(UIEvent * _Nullable)event SWIFT_WARN_UNUSED_RESULT;
- (void)bindTitle:(NSString * _Nonnull)title themed:(id <FSPThemed> _Nonnull)themed;
- (void)setVisible:(BOOL)visible animated:(BOOL)animated;
- (nonnull instancetype)initWithFrame:(CGRect)frame SWIFT_UNAVAILABLE;
@end

SWIFT_CLASS("_TtC14SmartPromoCore19FSPSectionTitleView")
@interface FSPSectionTitleView : UICollectionReusableView
@property (nonatomic, readonly, strong) UILabel * _Nonnull titleLabel;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS("_TtC14SmartPromoCore14FSPShimmerView")
@interface FSPShimmerView : UIView
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder SWIFT_UNAVAILABLE;
- (void)didMoveToSuperview;
- (void)didMoveToWindow;
- (void)layoutSubviews;
- (void)startShimmer;
- (void)stopShimmer;
- (nonnull instancetype)initWithFrame:(CGRect)frame SWIFT_UNAVAILABLE;
@end

@class NSUserDefaults;
SWIFT_CLASS("_TtC14SmartPromoCore15FSPUserDefaults")
@interface FSPUserDefaults : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) NSUserDefaults * _Nonnull shared;)
+ (NSUserDefaults * _Nonnull)shared SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@interface UIView (SWIFT_EXTENSION(SmartPromoCore))
- (void)applyShadow;
- (void)applyShadow:(CGFloat)cornerRadius;
@end

#endif // defined(__OBJC__)
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#if defined(__cplusplus)
#endif
#pragma clang diagnostic pop
#endif

#else
#error unsupported Swift architecture
#endif
